# fly.toml generated for 'lamenace'
app = "lamenace"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  KEEPALIVE = "1"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/"

[mounts]
  source = "bot_data"
  destination = "/data"
  initial_size = "1gb"
